# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('s_number', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=32)),
                ('height', models.DecimalField(decimal_places=4, max_digits=7)),
                ('longtitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
    ]
