# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 03:24
from __future__ import unicode_literals

from django.db import migrations

def initial_stations(apps, schema_editor):
    Station = apps.get_model('stations', 'Station')
    Station(s_number=u'455850', name=u'五分山雷達站', height='756', longtitude='121.7812', latitude='25.0712').save()
    Station(s_number=u'466880', name=u'板橋', height='9.7', longtitude='121.4420', latitude='24.9976').save()


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_stations),
    ]
